apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: springapp-pod
      labels:
        app: myapp
        tier: front-end
    spec:
      containers:
      - name: springapp
        image: yanivomc/spring-music:latest
      ports: 
      - containerPort: 8080
