apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
  labels:
    app: app2
spec:
  template:

    metadata:
      name: app2
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
        
  replicas: 1
  selector:
    matchLabels:
      app: app2
